services:
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=employee_service
      - POSTGRES_DB=employee_service
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=carrot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"