spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/employee_service
    username: employee_service
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: rabbit
    password: carrot
message-broker:
    event-queue:
      employee-event-queue: employee-events
      employee-event-dead-letter-queue: employee-event-dead-letter-queue
      employee-event-dead-letter-exchange: employee-event-dead-letter-exchange
    notification-queue:
      employee-notification-exchange: employee-notification-exchange
      employee-notification-routing-key: com.takeaway.employee.notification