server:
  port: 8888
  error.include-message: always
  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_service
    username: employee_service
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: carrot
    queues:
      employeeQueue: employee-events
    exchanges:
      employeeExchange: employee-exchange
    bindings:
      routing-key: com.takeaway.employee.modified